// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: random.proto

package random

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the max number length
type RandomNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxLength string `protobuf:"bytes,1,opt,name=maxLength,proto3" json:"maxLength,omitempty"`
}

func (x *RandomNumberRequest) Reset() {
	*x = RandomNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumberRequest) ProtoMessage() {}

func (x *RandomNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_random_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumberRequest.ProtoReflect.Descriptor instead.
func (*RandomNumberRequest) Descriptor() ([]byte, []int) {
	return file_random_proto_rawDescGZIP(), []int{0}
}

func (x *RandomNumberRequest) GetMaxLength() string {
	if x != nil {
		return x.MaxLength
	}
	return ""
}

// The response message containing the number
type RandomNumberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *RandomNumberReply) Reset() {
	*x = RandomNumberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumberReply) ProtoMessage() {}

func (x *RandomNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_random_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumberReply.ProtoReflect.Descriptor instead.
func (*RandomNumberReply) Descriptor() ([]byte, []int) {
	return file_random_proto_rawDescGZIP(), []int{1}
}

func (x *RandomNumberReply) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_random_proto protoreflect.FileDescriptor

var file_random_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x33, 0x0a, 0x13, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x2b, 0x0a, 0x11, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xa7, 0x01, 0x0a, 0x06, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x12, 0x50, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_random_proto_rawDescOnce sync.Once
	file_random_proto_rawDescData = file_random_proto_rawDesc
)

func file_random_proto_rawDescGZIP() []byte {
	file_random_proto_rawDescOnce.Do(func() {
		file_random_proto_rawDescData = protoimpl.X.CompressGZIP(file_random_proto_rawDescData)
	})
	return file_random_proto_rawDescData
}

var file_random_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_random_proto_goTypes = []interface{}{
	(*RandomNumberRequest)(nil), // 0: random.RandomNumberRequest
	(*RandomNumberReply)(nil),   // 1: random.RandomNumberReply
}
var file_random_proto_depIdxs = []int32{
	0, // 0: random.Random.GenerateRandomNumber:input_type -> random.RandomNumberRequest
	0, // 1: random.Random.StreamNumbers:input_type -> random.RandomNumberRequest
	1, // 2: random.Random.GenerateRandomNumber:output_type -> random.RandomNumberReply
	1, // 3: random.Random.StreamNumbers:output_type -> random.RandomNumberReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_random_proto_init() }
func file_random_proto_init() {
	if File_random_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_random_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_random_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_random_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_random_proto_goTypes,
		DependencyIndexes: file_random_proto_depIdxs,
		MessageInfos:      file_random_proto_msgTypes,
	}.Build()
	File_random_proto = out.File
	file_random_proto_rawDesc = nil
	file_random_proto_goTypes = nil
	file_random_proto_depIdxs = nil
}
